### ISSUE TITLE
Error on Import

### ISSUE THREAD

**Issue by r0f1** [chendaniely/pyprojroot#1]
Hi, I get the following error on import. What can I do?

```sh
flo@comp:/projects/bla$ sudo pip3 install pyprojroot
Requirement already satisfied: pyprojroot in /usr/local/lib/python3.5/dist-packages (0.1.1)
flo@comp:/projects/bla$ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyprojroot import here
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pyprojroot/__init__.py", line 1, in <module>
    from .pyprojroot import *
  File "/usr/local/lib/python3.5/dist-packages/pyprojroot/pyprojroot.py", line 22
    warnings.warn(f"Path doesn't exist: {pth}")
                                             ^
SyntaxError: invalid syntax
```

**Comment by chendaniely** [comment]
Oofs. It's using f-strings which is a python 3.6 feature...

**Comment by r0f1** [comment]
Alright. Thanks :)

**Comment by chendaniely** [comment]
@r0f1 I changed the string to use the older `.format` instead of f-strings in e9709ef3730009f02b856b08ececb0453aa9fc28 so give it another go

**Comment by chendaniely** [comment]
the version should be 0.1.2

`pip install pyprojroot==0.1.2`
